//! ast-grep patterns for different languages.
//!
//! Centralized pattern definitions for symbol extraction.
//!
//! Generated by `xiuxian_macros::patterns!` macro.

/// Python class pattern: `class $NAME`
pub const PYTHON_CLASS: &str = "class $NAME";
/// Python function pattern: `def $NAME`
pub const PYTHON_DEF: &str = "def $NAME";
/// Python async function pattern: `async def $NAME`
pub const PYTHON_ASYNC_DEF: &str = "async def $NAME";

/// Rust struct pattern: `pub struct $NAME`
pub const RUST_STRUCT: &str = "pub struct $NAME";
/// Rust function pattern: `pub fn $NAME`
pub const RUST_FN: &str = "pub fn $NAME";
/// Rust enum pattern: `enum $NAME`
pub const RUST_ENUM: &str = "enum $NAME";
/// Rust trait pattern: `trait $NAME`
pub const RUST_TRAIT: &str = "trait $NAME";
/// Rust impl pattern: `impl $NAME`
pub const RUST_IMPL: &str = "impl $NAME";

/// JavaScript class pattern: `class $NAME`
pub const JS_CLASS: &str = "class $NAME";
/// JavaScript function pattern: `function $NAME`
pub const JS_FN: &str = "function $NAME";

/// TypeScript interface pattern: `interface $NAME`
pub const TS_INTERFACE: &str = "interface $NAME";

/// Go patterns
/// Go struct pattern: `type $NAME struct`
pub const GO_STRUCT: &str = "type $NAME struct";
/// Go function pattern: `func $NAME`
pub const GO_FN: &str = "func $NAME";

/// Java patterns
/// Java class pattern: `class $NAME`
pub const JAVA_CLASS: &str = "class $NAME";
/// Java method pattern: `$NAME(`
pub const JAVA_METHOD: &str = "$NAME(";

// ============================================================================
// Legacy aliases for backwards compatibility
// ============================================================================

/// @deprecated Use `PYTHON_CLASS` instead
pub const PYTHON_CLASS_PATTERN: &str = PYTHON_CLASS;
/// @deprecated Use `PYTHON_DEF` instead
pub const PYTHON_DEF_PATTERN: &str = PYTHON_DEF;
/// @deprecated Use `PYTHON_ASYNC_DEF` instead
pub const PYTHON_ASYNC_DEF_PATTERN: &str = PYTHON_ASYNC_DEF;
/// @deprecated Use `RUST_STRUCT` instead
pub const RUST_STRUCT_PATTERN: &str = RUST_STRUCT;
/// @deprecated Use `RUST_FN` instead
pub const RUST_FN_PATTERN: &str = RUST_FN;
/// @deprecated Use `RUST_ENUM` instead
pub const RUST_ENUM_PATTERN: &str = RUST_ENUM;
/// @deprecated Use `RUST_TRAIT` instead
pub const RUST_TRAIT_PATTERN: &str = RUST_TRAIT;
/// @deprecated Use `RUST_IMPL` instead
pub const RUST_IMPL_PATTERN: &str = RUST_IMPL;
/// @deprecated Use `JS_CLASS` instead
pub const JS_CLASS_PATTERN: &str = JS_CLASS;
/// @deprecated Use `JS_FN` instead
pub const JS_FN_PATTERN: &str = JS_FN;
/// @deprecated Use `TS_INTERFACE` instead
pub const TS_INTERFACE_PATTERN: &str = TS_INTERFACE;

/// All patterns as a const array for iteration
pub const ALL_PATTERNS: &[(&str, &str)] = &[
    ("PYTHON_CLASS", PYTHON_CLASS),
    ("PYTHON_DEF", PYTHON_DEF),
    ("PYTHON_ASYNC_DEF", PYTHON_ASYNC_DEF),
    ("RUST_STRUCT", RUST_STRUCT),
    ("RUST_FN", RUST_FN),
    ("RUST_ENUM", RUST_ENUM),
    ("RUST_TRAIT", RUST_TRAIT),
    ("RUST_IMPL", RUST_IMPL),
    ("JS_CLASS", JS_CLASS),
    ("JS_FN", JS_FN),
    ("TS_INTERFACE", TS_INTERFACE),
    ("GO_STRUCT", GO_STRUCT),
    ("GO_FN", GO_FN),
    ("JAVA_CLASS", JAVA_CLASS),
    ("JAVA_METHOD", JAVA_METHOD),
];

/// Patterns grouped by language
pub mod python {
    use super::{PYTHON_ASYNC_DEF, PYTHON_CLASS, PYTHON_DEF};

    /// Python symbol extraction patterns.
    pub const PATTERNS: &[(&str, &str)] = &[
        ("CLASS", PYTHON_CLASS),
        ("DEF", PYTHON_DEF),
        ("ASYNC_DEF", PYTHON_ASYNC_DEF),
    ];
}

/// Rust symbol extraction patterns.
pub mod rust {
    use super::{RUST_ENUM, RUST_FN, RUST_IMPL, RUST_STRUCT, RUST_TRAIT};

    /// Rust symbol extraction patterns.
    pub const PATTERNS: &[(&str, &str)] = &[
        ("STRUCT", RUST_STRUCT),
        ("FN", RUST_FN),
        ("ENUM", RUST_ENUM),
        ("TRAIT", RUST_TRAIT),
        ("IMPL", RUST_IMPL),
    ];
}

/// JavaScript symbol extraction patterns.
pub mod javascript {
    use super::{JS_CLASS, JS_FN};

    /// JavaScript symbol extraction patterns.
    pub const PATTERNS: &[(&str, &str)] = &[("CLASS", JS_CLASS), ("FN", JS_FN)];
}

/// TypeScript symbol extraction patterns.
pub mod typescript {
    use super::TS_INTERFACE;

    /// TypeScript symbol extraction patterns.
    pub const PATTERNS: &[(&str, &str)] = &[("INTERFACE", TS_INTERFACE)];
}

/// Go symbol extraction patterns.
pub mod go {
    use super::{GO_FN, GO_STRUCT};

    /// Go symbol extraction patterns.
    pub const PATTERNS: &[(&str, &str)] = &[("STRUCT", GO_STRUCT), ("FN", GO_FN)];
}

/// Java symbol extraction patterns.
pub mod java {
    use super::{JAVA_CLASS, JAVA_METHOD};

    /// Java symbol extraction patterns.
    pub const PATTERNS: &[(&str, &str)] = &[("CLASS", JAVA_CLASS), ("METHOD", JAVA_METHOD)];
}
