//! Canonical event identifiers for session, memory, and dedup observability.

/// Stable event IDs for session lifecycle, memory persistence, and webhook dedup.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum SessionEvent {
    SessionBackendEnabled,
    SessionValkeyConnected,
    SessionValkeyCommandRetrySucceeded,
    SessionValkeyCommandRetryFailed,
    SessionValkeyPipelineRetrySucceeded,
    SessionValkeyPipelineRetryFailed,
    SessionMessagesAppended,
    SessionMessagesReplaced,
    SessionMessagesLoaded,
    SessionMessagesCleared,
    SessionStreamEventPublished,
    SessionWindowSlotsAppended,
    SessionWindowSlotsLoaded,
    SessionWindowStatsLoaded,
    SessionWindowCleared,
    SessionSummarySegmentAppended,
    SessionSummarySegmentsLoaded,
    SessionSummaryCleared,
    SessionWindowSlotsDrained,
    BoundedRecentMessagesLoaded,
    BoundedTurnAppended,
    BoundedStatsLoaded,
    BoundedCleared,
    BoundedTurnsDrained,
    BoundedSummarySegmentAppended,
    BoundedSummarySegmentsLoaded,
    SessionGateBackendInitialized,
    SessionGateLeaseAcquired,
    SessionGateLeaseAcquireTimeout,
    SessionGateLeaseRenewed,
    SessionGateLeaseRenewalFailed,
    SessionGateLeaseReleased,
    ContextWindowReset,
    ContextWindowResumeMissing,
    ContextWindowResumed,
    ContextWindowSnapshotDropped,
    ContextWindowSnapshotInspected,
    ContextBackupCaptured,
    RouteDecisionSelected,
    RouteFallbackApplied,
    RouteGraphPlanGenerated,
    RouteGraphStepStarted,
    RouteGraphStepSucceeded,
    RouteGraphStepFailed,
    RouteGraphExecutionCompleted,
    RouteGraphExecutionRerouted,
    RouteTraceEmitted,
    ReflectionLifecycleTransition,
    ReflectionLifecycleError,
    ReflectionPolicyHintStored,
    ReflectionPolicyHintApplied,
    InjectionSnapshotCreated,
    InjectionBlockDropped,
    InjectionBlockTruncated,
    MemoryBackendInitialized,
    MemoryStateLoadSucceeded,
    MemoryStateLoadFailed,
    MemoryStateSaveSucceeded,
    MemoryStateSaveFailed,
    MemoryTurnStoreFailed,
    MemoryConsolidationStoreFailed,
    MemoryEmbeddingDimMismatch,
    MemoryRecallPlanned,
    MemoryRecallInjected,
    MemoryRecallSkipped,
    MemoryRecallCreditApplied,
    MemoryRecallFeedbackUpdated,
    MemoryGateEvaluated,
    MemoryPromoted,
    MemoryDecayApplied,
    MemoryStreamConsumerStarted,
    MemoryStreamConsumerDisabled,
    MemoryStreamConsumerGroupReady,
    MemoryStreamConsumerEventProcessed,
    MemoryStreamConsumerReadFailed,
    DedupBackendInitialized,
    DedupDuplicateDetected,
    DedupUpdateAccepted,
    DedupValkeyConnected,
    DedupSetNxRetrySucceeded,
    DedupSetNxRetryFailed,
    DedupEvaluated,
}

impl SessionEvent {
    /// String identifier for log filtering and aggregation.
    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::SessionValkeyConnected => "session.valkey.connected",
            Self::SessionBackendEnabled => "session.backend.enabled",
            Self::SessionValkeyCommandRetrySucceeded => "session.valkey.command.retry_succeeded",
            Self::SessionValkeyCommandRetryFailed => "session.valkey.command.retry_failed",
            Self::SessionValkeyPipelineRetrySucceeded => "session.valkey.pipeline.retry_succeeded",
            Self::SessionValkeyPipelineRetryFailed => "session.valkey.pipeline.retry_failed",
            Self::SessionMessagesAppended => "session.messages.appended",
            Self::SessionMessagesReplaced => "session.messages.replaced",
            Self::SessionMessagesLoaded => "session.messages.loaded",
            Self::SessionMessagesCleared => "session.messages.cleared",
            Self::SessionStreamEventPublished => "session.stream_event.published",
            Self::SessionWindowSlotsAppended => "session.window_slots.appended",
            Self::SessionWindowSlotsLoaded => "session.window_slots.loaded",
            Self::SessionWindowStatsLoaded => "session.window_stats.loaded",
            Self::SessionWindowCleared => "session.window.cleared",
            Self::SessionSummarySegmentAppended => "session.summary_segment.appended",
            Self::SessionSummarySegmentsLoaded => "session.summary_segments.loaded",
            Self::SessionSummaryCleared => "session.summary.cleared",
            Self::SessionWindowSlotsDrained => "session.window_slots.drained",
            Self::BoundedRecentMessagesLoaded => "session.bounded.recent_messages.loaded",
            Self::BoundedTurnAppended => "session.bounded.turn.appended",
            Self::BoundedStatsLoaded => "session.bounded.stats.loaded",
            Self::BoundedCleared => "session.bounded.cleared",
            Self::BoundedTurnsDrained => "session.bounded.turns.drained",
            Self::BoundedSummarySegmentAppended => "session.bounded.summary_segment.appended",
            Self::BoundedSummarySegmentsLoaded => "session.bounded.summary_segments.loaded",
            Self::SessionGateBackendInitialized => "session.gate.backend.initialized",
            Self::SessionGateLeaseAcquired => "session.gate.lease.acquired",
            Self::SessionGateLeaseAcquireTimeout => "session.gate.lease.acquire_timeout",
            Self::SessionGateLeaseRenewed => "session.gate.lease.renewed",
            Self::SessionGateLeaseRenewalFailed => "session.gate.lease.renewal_failed",
            Self::SessionGateLeaseReleased => "session.gate.lease.released",
            Self::ContextWindowReset => "session.context_window.reset",
            Self::ContextWindowResumeMissing => "session.context_window.resume_missing",
            Self::ContextWindowResumed => "session.context_window.resumed",
            Self::ContextWindowSnapshotDropped => "session.context_window.snapshot_dropped",
            Self::ContextWindowSnapshotInspected => "session.context_window.snapshot_inspected",
            Self::ContextBackupCaptured => "session.context_backup.captured",
            Self::RouteDecisionSelected => "session.route.decision_selected",
            Self::RouteFallbackApplied => "session.route.fallback_applied",
            Self::RouteGraphPlanGenerated => "session.route.graph_plan_generated",
            Self::RouteGraphStepStarted => "session.route.graph_step_started",
            Self::RouteGraphStepSucceeded => "session.route.graph_step_succeeded",
            Self::RouteGraphStepFailed => "session.route.graph_step_failed",
            Self::RouteGraphExecutionCompleted => "session.route.graph_execution_completed",
            Self::RouteGraphExecutionRerouted => "session.route.graph_execution_rerouted",
            Self::RouteTraceEmitted => "session.route.trace_emitted",
            Self::ReflectionLifecycleTransition => "agent.reflection.lifecycle.transition",
            Self::ReflectionLifecycleError => "agent.reflection.lifecycle.error",
            Self::ReflectionPolicyHintStored => "agent.reflection.policy_hint.stored",
            Self::ReflectionPolicyHintApplied => "agent.reflection.policy_hint.applied",
            Self::InjectionSnapshotCreated => "session.injection.snapshot_created",
            Self::InjectionBlockDropped => "session.injection.block_dropped",
            Self::InjectionBlockTruncated => "session.injection.block_truncated",
            Self::MemoryBackendInitialized => "agent.memory.backend.initialized",
            Self::MemoryStateLoadSucceeded => "agent.memory.state_load_succeeded",
            Self::MemoryStateLoadFailed => "agent.memory.state_load_failed",
            Self::MemoryStateSaveSucceeded => "agent.memory.state_save_succeeded",
            Self::MemoryStateSaveFailed => "agent.memory.state_save_failed",
            Self::MemoryTurnStoreFailed => "agent.memory.turn_store_failed",
            Self::MemoryConsolidationStoreFailed => "agent.memory.consolidation_store_failed",
            Self::MemoryEmbeddingDimMismatch => "agent.memory.embedding_dim_mismatch",
            Self::MemoryRecallPlanned => "agent.memory.recall.planned",
            Self::MemoryRecallInjected => "agent.memory.recall.injected",
            Self::MemoryRecallSkipped => "agent.memory.recall.skipped",
            Self::MemoryRecallCreditApplied => "agent.memory.recall.credit_applied",
            Self::MemoryRecallFeedbackUpdated => "agent.memory.recall.feedback_updated",
            Self::MemoryGateEvaluated => "agent.memory.gate.evaluated",
            Self::MemoryPromoted => "agent.memory.promoted",
            Self::MemoryDecayApplied => "agent.memory.decay.applied",
            Self::MemoryStreamConsumerStarted => "agent.memory.stream_consumer.started",
            Self::MemoryStreamConsumerDisabled => "agent.memory.stream_consumer.disabled",
            Self::MemoryStreamConsumerGroupReady => "agent.memory.stream_consumer.group_ready",
            Self::MemoryStreamConsumerEventProcessed => {
                "agent.memory.stream_consumer.event_processed"
            }
            Self::MemoryStreamConsumerReadFailed => "agent.memory.stream_consumer.read_failed",
            Self::DedupBackendInitialized => "telegram.dedup.backend.initialized",
            Self::DedupDuplicateDetected => "telegram.dedup.duplicate_detected",
            Self::DedupUpdateAccepted => "telegram.dedup.update_accepted",
            Self::DedupValkeyConnected => "telegram.dedup.valkey.connected",
            Self::DedupSetNxRetrySucceeded => "telegram.dedup.set_nx.retry_succeeded",
            Self::DedupSetNxRetryFailed => "telegram.dedup.set_nx.retry_failed",
            Self::DedupEvaluated => "telegram.dedup.evaluated",
        }
    }

    pub(crate) const ALL: [Self; 82] = [
        Self::SessionBackendEnabled,
        Self::SessionValkeyConnected,
        Self::SessionValkeyCommandRetrySucceeded,
        Self::SessionValkeyCommandRetryFailed,
        Self::SessionValkeyPipelineRetrySucceeded,
        Self::SessionValkeyPipelineRetryFailed,
        Self::SessionMessagesAppended,
        Self::SessionMessagesReplaced,
        Self::SessionMessagesLoaded,
        Self::SessionMessagesCleared,
        Self::SessionStreamEventPublished,
        Self::SessionWindowSlotsAppended,
        Self::SessionWindowSlotsLoaded,
        Self::SessionWindowStatsLoaded,
        Self::SessionWindowCleared,
        Self::SessionSummarySegmentAppended,
        Self::SessionSummarySegmentsLoaded,
        Self::SessionSummaryCleared,
        Self::SessionWindowSlotsDrained,
        Self::BoundedRecentMessagesLoaded,
        Self::BoundedTurnAppended,
        Self::BoundedStatsLoaded,
        Self::BoundedCleared,
        Self::BoundedTurnsDrained,
        Self::BoundedSummarySegmentAppended,
        Self::BoundedSummarySegmentsLoaded,
        Self::SessionGateBackendInitialized,
        Self::SessionGateLeaseAcquired,
        Self::SessionGateLeaseAcquireTimeout,
        Self::SessionGateLeaseRenewed,
        Self::SessionGateLeaseRenewalFailed,
        Self::SessionGateLeaseReleased,
        Self::ContextWindowReset,
        Self::ContextWindowResumeMissing,
        Self::ContextWindowResumed,
        Self::ContextWindowSnapshotDropped,
        Self::ContextWindowSnapshotInspected,
        Self::ContextBackupCaptured,
        Self::RouteDecisionSelected,
        Self::RouteFallbackApplied,
        Self::RouteGraphPlanGenerated,
        Self::RouteGraphStepStarted,
        Self::RouteGraphStepSucceeded,
        Self::RouteGraphStepFailed,
        Self::RouteGraphExecutionCompleted,
        Self::RouteGraphExecutionRerouted,
        Self::RouteTraceEmitted,
        Self::ReflectionLifecycleTransition,
        Self::ReflectionLifecycleError,
        Self::ReflectionPolicyHintStored,
        Self::ReflectionPolicyHintApplied,
        Self::InjectionSnapshotCreated,
        Self::InjectionBlockDropped,
        Self::InjectionBlockTruncated,
        Self::MemoryBackendInitialized,
        Self::MemoryStateLoadSucceeded,
        Self::MemoryStateLoadFailed,
        Self::MemoryStateSaveSucceeded,
        Self::MemoryStateSaveFailed,
        Self::MemoryTurnStoreFailed,
        Self::MemoryConsolidationStoreFailed,
        Self::MemoryEmbeddingDimMismatch,
        Self::MemoryRecallPlanned,
        Self::MemoryRecallInjected,
        Self::MemoryRecallSkipped,
        Self::MemoryRecallCreditApplied,
        Self::MemoryRecallFeedbackUpdated,
        Self::MemoryGateEvaluated,
        Self::MemoryPromoted,
        Self::MemoryDecayApplied,
        Self::MemoryStreamConsumerStarted,
        Self::MemoryStreamConsumerDisabled,
        Self::MemoryStreamConsumerGroupReady,
        Self::MemoryStreamConsumerEventProcessed,
        Self::MemoryStreamConsumerReadFailed,
        Self::DedupBackendInitialized,
        Self::DedupDuplicateDetected,
        Self::DedupUpdateAccepted,
        Self::DedupValkeyConnected,
        Self::DedupSetNxRetrySucceeded,
        Self::DedupSetNxRetryFailed,
        Self::DedupEvaluated,
    ];
}

fn lint_symbol_probe() {
    let _ = &SessionEvent::ALL;
}

const _: fn() = lint_symbol_probe;
