"""
factory.py - Automated Skill Synthesis

Core Logic: Generate standard Omni Skill files from candidate patterns.

Supports both legacy session-based skills and new trace-based skills.
Safety: All generated skills go to quarantine directory for review.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from omni.foundation.config.logging import get_logger
from omni.foundation.config.skills import SKILLS_DIR

from .prompts import render_xml_guide
from .schemas import CandidateSkill, CrystallizationResult

logger = get_logger("omni.evolution.factory")


# =============================================================================
# Skill Templates
# =============================================================================

PYTHON_SKILL_TEMPLATE = '''"""
{skill_name} - Auto-generated by Omni-Dev Fusion Factory

{description}

Generated: {timestamp}
Source: {trace_id}
Reasoning: {reasoning}
"""

from __future__ import annotations

from typing import Any

from omni.core.skills.runtime.decorators import skill_command
from omni.core.skills.runtime.omni_cell import OmniCellRunner


@skill_command(
    name="{skill_name}",
    description="{description}",
    category="{category}",
)
async def {skill_name}(
{param_declarations}
) -> dict[str, Any]:
    """
    {description}

{param_docs}

    Returns:
        Dict with execution results
    """
    runner = OmniCellRunner()

    # Nushell script with parameter placeholders
    script = r"""
{nushell_script}
    """

    # Execute with parameters
    result = await runner.execute(script)
    return {{"success": True, "data": result}}


if __name__ == "__main__":
    from omni.foundation.utils import run_async_blocking

    run_async_blocking({skill_name}())
'''

SKILL_MD_TEMPLATE = """# {skill_name}

{description}

**Category**: {category}
**Generated**: {timestamp}
**Source Trace**: `{trace_id}`
**Confidence**: {confidence:.0%}

## Overview

This skill was automatically generated from execution traces by the Evolution System.

**Reasoning**: {reasoning}

## Usage

```python
from omni.skills.{category} import {skill_name}

result = await {skill_name}(
{param_examples})
```

## XML Usage Guide (for LLM)

```xml
{xml_guide}
```

## Parameters

| Name | Type | Description |
|------|------|-------------|
{param_table}

## Nushell Script

```nushell
{nushell_script}
```

## FAQ

{faq_section}

## Original Context

> {original_task}
"""

README_TEMPLATE = """# {skill_name}

{description}

Auto-generated skill from Omni-Dev Fusion Evolution System.

## Details

- **Category**: {category}
- **Generated**: {timestamp}
- **Complexity**: {complexity}
- **Confidence**: {confidence:.0%}

## Source

Extracted from task: {original_task}
"""


# =============================================================================
# Utility Functions
# =============================================================================


def _sanitize_name(name: str) -> str:
    """Convert intent string to valid Python identifier."""
    safe = name.lower().strip()
    safe = safe.replace(" ", "_").replace("-", "_").replace(".", "_")
    safe = "".join(c if c.isalnum() or c == "_" else "_" for c in safe)
    if safe[0].isdigit():
        safe = f"skill_{safe}"
    return safe


def _to_class_name(snake_name: str) -> str:
    """Convert snake_case to PascalCase."""
    parts = snake_name.split("_")
    return "".join(p.title() for p in parts if p)


def _generate_param_declarations(parameters: dict[str, str]) -> str:
    """Generate parameter declarations for function signature."""
    lines = []
    for name, desc in parameters.items():
        safe_name = _sanitize_name(name)
        # Simple type inference from name
        if "path" in name.lower() or "file" in name.lower():
            param_type = "Path"
        elif "count" in name.lower() or "num" in name.lower():
            param_type = "int"
        elif "pattern" in name.lower():
            param_type = "str"
        else:
            param_type = "str"
        lines.append(f"    {safe_name}: {param_type} = None,  # {desc}")
    return ",\n".join(lines)


def _generate_param_docs(parameters: dict[str, str]) -> str:
    """Generate parameter documentation."""
    lines = []
    for name, desc in parameters.items():
        safe_name = _sanitize_name(name)
        lines.append(f"    - {safe_name}: {desc}")
    return "\n".join(lines)


def _generate_param_examples(parameters: dict[str, str]) -> str:
    """Generate parameter examples for SKILL.md."""
    lines = []
    for name in parameters:
        safe_name = _sanitize_name(name)
        if "path" in name.lower():
            lines.append(f'    {safe_name}="/path/to/file",')
        elif "pattern" in name.lower():
            lines.append(f'    {safe_name}="*.py",')
        else:
            lines.append(f'    {safe_name}="value",')
    return "\n".join(lines)


def _generate_param_table(parameters: dict[str, str]) -> str:
    """Generate parameter table for SKILL.md."""
    lines = []
    for name, desc in parameters.items():
        safe_name = _sanitize_name(name)
        if "path" in safe_name or "file" in safe_name:
            ptype = "Path"
        elif "count" in safe_name or "num" in safe_name:
            ptype = "int"
        else:
            ptype = "str"
        lines.append(f"| {safe_name} | {ptype} | {desc} |")
    return "\n".join(lines)


# =============================================================================
# Skill Factory
# =============================================================================


class SkillFactory:
    """
    Manufactures physical skill files from CandidateSkill definitions.

    Safety Features:
    - All generated skills go to `quarantine/` directory first
    - Must be reviewed/promoted before becoming active
    - Static analysis validation available
    """

    def __init__(
        self,
        skills_dir: Path | None = None,
        quarantine_dir: Path | None = None,
    ):
        """Initialize the skill factory.

        Args:
            skills_dir: Directory for active skills (default: assets/skills/learned)
            quarantine_dir: Directory for pending review (default: quarantine/)
        """
        if skills_dir is None:
            skills_dir = SKILLS_DIR() / "learned"

        if quarantine_dir is None:
            quarantine_dir = skills_dir / "quarantine"

        self.skills_dir = Path(skills_dir)
        self.quarantine_dir = Path(quarantine_dir)

        # Ensure directories exist
        self.skills_dir.mkdir(parents=True, exist_ok=True)
        self.quarantine_dir.mkdir(parents=True, exist_ok=True)

    async def manufacture(
        self,
        candidate: CandidateSkill,
        skip_quarantine: bool = False,
    ) -> CrystallizationResult:
        """
        Generate skill files from a CandidateSkill.

        Args:
            candidate: The skill blueprint to manufacture
            skip_quarantine: If True, skip quarantine (for testing)

        Returns:
            CrystallizationResult with paths and status
        """
        skill_name = _sanitize_name(candidate.suggested_name)
        timestamp = datetime.now().isoformat()

        # Choose output directory
        if skip_quarantine:
            output_dir = self.skills_dir / candidate.category
        else:
            output_dir = self.quarantine_dir / candidate.category

        output_dir.mkdir(parents=True, exist_ok=True)

        files_created: list[str] = []

        try:
            # 1. Generate Python implementation
            py_content = self._render_python_skill(candidate, skill_name, timestamp)
            py_path = output_dir / f"{skill_name}.py"
            py_path.write_text(py_content)
            files_created.append(str(py_path))

            # 2. Generate SKILL.md documentation
            md_content = self._render_skill_md(candidate, skill_name, timestamp)
            md_path = output_dir / "SKILL.md"
            md_path.write_text(md_content)
            files_created.append(str(md_path))

            # 3. Generate README.md
            readme_content = self._render_readme(candidate, skill_name, timestamp)
            readme_path = output_dir / "README.md"
            readme_path.write_text(readme_content)
            files_created.append(str(readme_path))

            logger.info(
                "factory.skill_created",
                skill_name=skill_name,
                category=candidate.category,
                files=files_created,
            )

            return CrystallizationResult(
                success=True,
                skill_path=str(output_dir),
                skill_name=skill_name,
                files_created=files_created,
            )

        except Exception as e:
            logger.error(
                "factory.manufacture_failed",
                skill=candidate.suggested_name,
                error=str(e),
            )
            return CrystallizationResult(
                success=False,
                error=str(e),
            )

    def _render_python_skill(
        self,
        candidate: CandidateSkill,
        skill_name: str,
        timestamp: str,
    ) -> str:
        """Render Python skill file from template."""
        param_decls = _generate_param_declarations(candidate.parameters)
        param_docs = _generate_param_docs(candidate.parameters)

        # Escape curly braces for .format()
        escaped_script = candidate.nushell_script.replace("{", "{{").replace("}", "}}")

        return PYTHON_SKILL_TEMPLATE.format(
            skill_name=skill_name,
            description=candidate.description,
            category=candidate.category,
            timestamp=timestamp,
            trace_id=candidate.trace_id,
            reasoning=candidate.reasoning,
            param_declarations=param_decls,
            param_docs=param_docs,
            nushell_script=escaped_script,
        )

    def _render_skill_md(
        self,
        candidate: CandidateSkill,
        skill_name: str,
        timestamp: str,
    ) -> str:
        """Render SKILL.md documentation from template with XML usage guide."""
        param_examples = _generate_param_examples(candidate.parameters)
        param_table = _generate_param_table(candidate.parameters)

        # Generate XML usage guide
        xml_guide = render_xml_guide(
            skill_name=skill_name,
            description=candidate.description,
            original_task=candidate.original_task,
            reasoning=candidate.reasoning,
            scenarios=candidate.usage_scenarios,
            faqs=candidate.faq_items,
        )

        # Generate FAQ section for human readers
        if candidate.faq_items:
            faq_section = "\n".join(
                f"**Q: {f.get('q', '')}**\nA: {f.get('a', '')}" for f in candidate.faq_items
            )
        else:
            faq_section = "_No FAQ items generated._"

        return SKILL_MD_TEMPLATE.format(
            skill_name=skill_name,
            description=candidate.description,
            category=candidate.category,
            timestamp=timestamp,
            trace_id=candidate.trace_id,
            confidence=candidate.confidence_score,
            reasoning=candidate.reasoning,
            param_examples=param_examples,
            param_table=param_table,
            nushell_script=candidate.nushell_script,
            xml_guide=xml_guide,
            faq_section=faq_section,
            original_task=candidate.original_task,
        )

    def _render_readme(
        self,
        candidate: CandidateSkill,
        skill_name: str,
        timestamp: str,
    ) -> str:
        """Render README.md from template."""
        return README_TEMPLATE.format(
            skill_name=skill_name,
            description=candidate.description,
            category=candidate.category,
            timestamp=timestamp,
            complexity=candidate.estimated_complexity,
            confidence=candidate.confidence_score,
            original_task=candidate.original_task,
        )


__all__ = [
    "CrystallizationResult",
    "SkillFactory",
]
