#!/usr/bin/env python3
"""Output helpers for Telegram group profile capture."""

from __future__ import annotations

import json
from collections import Counter
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path


def quote_env(value: str) -> str:
    """Single-quote env value with portable shell escaping."""
    return "'" + value.replace("'", "'\"'\"'") + "'"


def write_profile(
    *,
    output_json: Path,
    output_env: Path,
    ordered_titles: list[str],
    discovered: dict[str, Any],
    user_id_override: int | None,
) -> None:
    """Write group mapping profile to JSON and companion env file."""
    present_titles = [title for title in ordered_titles if title in discovered]

    chosen_user_id: int | None = user_id_override
    if chosen_user_id is None:
        user_samples = [
            discovered[title].user_id for title in present_titles if discovered[title].user_id
        ]
        if user_samples:
            chosen_user_id = Counter(user_samples).most_common(1)[0][0]

    user_a = chosen_user_id
    user_b = chosen_user_id + 1 if chosen_user_id is not None else None
    user_c = chosen_user_id + 2 if chosen_user_id is not None else None

    session_aliases = ("a", "b", "c")
    sessions: dict[str, dict[str, object]] = {}
    for index, (alias, title) in enumerate(zip(session_aliases, present_titles, strict=False)):
        obs = discovered[title]
        alias_user = user_a if index == 0 else (user_b if index == 1 else user_c)
        sessions[alias] = {
            "title": title,
            "observed_title": obs.title,
            "chat_id": obs.chat_id,
            "chat_type": obs.chat_type,
            "user_id": alias_user,
            "line_index": obs.line_index,
        }

    profile = {
        "generated_at": datetime.now(UTC).isoformat(),
        "titles_order": ordered_titles,
        "present_titles": present_titles,
        "sessions": sessions,
    }

    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(
        json.dumps(profile, ensure_ascii=True, indent=2) + "\n", encoding="utf-8"
    )

    env_lines: list[str] = [
        "# Generated by scripts/channel/capture_telegram_group_profile.py",
        f"OMNI_TEST_GROUP_PROFILE_JSON={quote_env(str(output_json))}",
    ]

    def set_pair(key: str, value: str | int) -> None:
        if isinstance(value, int):
            env_lines.append(f"{key}={value}")
        else:
            env_lines.append(f"{key}={quote_env(value)}")

    if "a" in sessions:
        set_pair("OMNI_TEST_CHAT_ID", int(sessions["a"]["chat_id"]))
        set_pair("OMNI_TEST_CHAT_TITLE_A", str(sessions["a"]["title"]))
    if "b" in sessions:
        set_pair("OMNI_TEST_CHAT_B", int(sessions["b"]["chat_id"]))
        set_pair("OMNI_TEST_CHAT_TITLE_B", str(sessions["b"]["title"]))
    if "c" in sessions:
        set_pair("OMNI_TEST_CHAT_C", int(sessions["c"]["chat_id"]))
        set_pair("OMNI_TEST_CHAT_TITLE_C", str(sessions["c"]["title"]))
    if user_a is not None:
        set_pair("OMNI_TEST_USER_ID", user_a)
    if user_b is not None:
        set_pair("OMNI_TEST_USER_B", user_b)
    if user_c is not None:
        set_pair("OMNI_TEST_USER_C", user_c)

    output_env.parent.mkdir(parents=True, exist_ok=True)
    output_env.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
