{
  inputs,
  __inputs__,
  pkgs,
  config,
  lib,
}:
let
  inherit (inputs.omnibus.inputs.flops.inputs.dmerge) prepend append merge;
  initConfigs =
    (inputs.omnibus.units.configs {
      inputs = {
        inputs = {
          nixpkgs = __inputs__.nixpkgs-latest;
          inherit (inputs.omnibus.flake.inputs) git-hooks;
        };
      };
    }).exports.default;

  lefthook = initConfigs.lefthook;

  # Project scopes shared across conform and cog
  # Maps to: agent/how-to/git-workflow.md
  project-scopes = [
    # Python packages
    "foundation" # Foundation layer: config, logging, runtime
    "core" # Core agent modules
    "agent" # Agent modules
    "mcp-server" # MCP server implementation
    # Rust crates
    "rust" # Rust core implementation (omni-*)
    "rust-core" # Rust core implementation (alias for rust)
    "omni-ast" # AST parsing and analysis
    "omni-edit" # Code editing and batch operations
    "omni-io" # Safe file I/O operations
    "omni-lance" # LanceDB vector store integration
    "omni-security" # Security and sanitization
    "omni-sniffer" # Code structure analysis
    "omni-tags" # Tag extraction and management
    "omni-tokenizer" # BPE tokenization
    "omni-types" # Type unification across languages
    "omni-vector" # Vector store operations
    "skills-scanner" # Skill discovery and scanning
    "scanner" # Alias for skills-scanner
    "rust-bindings" # Python bindings via PyO3
    # Core infrastructure
    "skills" # Skill definitions and scripts
    "nix" # Infrastructure: devenv.nix, modules
    "docs" # Documentation
    "cli" # Tooling: justfile, lefthook
    "deps" # Dependency management
    "ci" # GitHub Actions, DevContainer
    "data" # JSONL examples, assets
    "mcp" # MCP application
    "mcp-core" # MCP core modules
    "inference" # AI inference engine
    "router" # Tool routing & intent
    "orchestrator" # Orchestrator module
    "git-ops" # Git operations tools
    "git-workflow" # Git workflow documentation
    "version" # Version bump commits
    "claude" # Claude configuration
  ];
  # Define generator configurations
  generators = [
    {
      name = "lefthook";
      gen =
        (config.omnibus.ops.mkNixago initConfigs.nixago-lefthook)
          initConfigs.lefthook.nix
          initConfigs.lefthook.shell
          initConfigs.lefthook.prettier
          {
            data = {
              pre-commit.commands = {
                prettier = {
                  exclude = append [
                    ".devcontainer.json" # Generated by nix, don't format
                    "CHANGELOG.md"
                    "packages/rust/crates/xiuxian-skills/resources/skill_metadata.schema.json"
                    # "agent/**"
                  ];
                };
                # Update knowledge XML with repomix
                "update-knowledge-xml" = {
                  glob = "agent/knowledge/**/*.md";
                  run = ''cd agent/knowledge && repomix --config repomix.json --output "$PRJ_ROOT"/.data/project_knowledge.xml '';
                };
                # Add ruff for Python formatting
                "format-python" = {
                  glob = "*.py";
                  exclude = [
                    "assets/skills/_template/**" # Template folder - not real code
                  ];
                  run = "uv run ruff format {staged_files}";
                };
                cog-check = {
                  run = "cog check";
                };
                format-rust = {
                  glob = "*.rs";
                  run = "rustfmt -- {staged_files}";
                };
                format-nickel = {
                  glob = "*.ncl";
                  run = "nickel format -- {staged_files}";
                };
              };
              commit-msg = lefthook.default.data.commit-msg;
              # Remove unnecessary commands from default pre-commit
              commands = builtins.removeAttrs lefthook.default.data.pre-commit.commands [
                "treefmt" # We use nixfmt instead
                # "hunspell" # Not needed for LLM-generated content
                # "typos" # Not needed for LLM-generated content
              ];
            };
          };
    }
    {
      name = "conform";
      gen =
        (config.omnibus.ops.mkNixago initConfigs.nixago-conform)
          initConfigs.conform.default
          {
            data.commit = {
              conventional = {
                scopes = append project-scopes;
              };
            };
          };
    }
    {
      name = "cog";
      gen =
        (config.omnibus.ops.mkNixago initConfigs.nixago-cog) initConfigs.cog.default
          {
            data = {
              scopes = project-scopes;
              changelog = {
                path = "CHANGELOG.md";
                template = "remote";
                remote = "github.com";
                repository = "omni-dev-fusion";
                owner = "tao3k";
                authors = [
                  {
                    username = "gtrunsec";
                    signature = "Guangtao";
                  }
                ];
              };
            };
          };
    }
  ];

  # Generate all hooks using map
  generatedHooks = map (g: g.gen) generators;
in
{
  config = {
    packages = lib.flatten (map (g: g.__passthru.packages) generatedHooks);
    enterShell = lib.concatMapStringsSep "\n" (g: g.shellHook) generatedHooks;
  };
}
